carts/urls.py
from django.urls import path
from carts import views
urlpatterns = [
    path('', views.cart_page, name='cart-page'),
    path('add_to_cart/<int:product_id>/', views.add_cart, name='add-to-cart'),
    path('suntract-from-cart/<int:product_id>/<int:cart_item_id>/', views.subtract_cart, name="subtract-cart"),
    path('delete/<int:product_id>/<int:cart_item_id>?', views.remove_item, name="delete-cart-item"),
    path('checkout/', views.check_out, name='checkout')
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace = "admin_honeypot" )),
    path("secure_panel_login/", admin.site.urls),
    path('', include("greatKart.urls")),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('account/', include('accounts.urls')),
    
    # ORDERS
    path('orders/',include('orders.urls')),
 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from store import views


urlpatterns = [
    path('', views.store, name='store-page'),
    path('submitReview/<int:product_id>/', views.submit_review, name='submit-review'),
    path('search/', views.search, name='search'),
    path('filter/<slug:category_slug>/',views.filter_category, name='filter-category'),
    path('<slug:category_slug>/<slug:product_slug>/',views.product_detail, name='product-detail'),
]

carts/models.py
from django.db import models
from store.models import Product, Variation
from accounts.models import Account
# Create your models here.


class Cart(models.Model):
    cart_id = models.CharField(max_length=50, blank=True, unique=True)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    user =  models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation = models.ManyToManyField(Variation, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)
    def sub_total(self):
        return round(self.product.price * self.quantity, 2)

    def __unicode__(self):
        return self.product

store/models.py
from django.db import models
from category.models import Category
from django.urls import path, reverse
from accounts.models import Account

class Product(models.Model):
    product_name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(max_length=500, blank=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='photos/products')
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('product-detail', args=[self.category.slug, self.slug])

    def __str__(self):
        return f'#{self.id} - {self.product_name}'


    def averageReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=models.Avg('rating'))
        avg = 0
        if reviews['average'] is not None:
            avg = float(reviews['average'])  
        return avg    

    def countReview(self):
        count = 0
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=models.Count('rating'))
        if reviews['count'] is not None:
            count = int(reviews['count'])
        return count    

class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_category='color', is_active=True)

    def sizes(self):
        return super(VariationManager, self).filter(variation_category='size', is_active=True)


variation_category_choice = (
    ('color', 'color'),
    ('size', 'size')
)


class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(
        max_length=100, choices=variation_category_choice)
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now=True)

    objects = VariationManager()

    def __str__(self):
        return self.variation_value


class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account,on_delete=models.CASCADE)
    subject = models.CharField(max_length=50, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True) 
    
    
    
    def __str__(self):
        return self.subject
    
 
 
 
 
class ProductGallery(models.Model):
      product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
      image = models.ImageField(upload_to='store/products', max_length=255)
      
      
      class Meta:
          verbose_name = 'productgallery'
          verbose_name_plural ='product gallery'
      
      
      def __str__(self):
          return self.product.product_name    

store/forms.py
from django import forms
from .models import ReviewRating


class ReviewForms(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['subject','review','rating']
        

carts/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from store import models as store_models
from carts import models as carts_models
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required

def __cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def cart_page(request, totalPay=0, quantity=0, cart_items=None):
    try:
        grand_totalPay = 0.0
        tax = 0.0
        if request.user.is_authenticated:
            cart_items = carts_models.CartItem.objects.filter(user = request.user, is_active = True)
        else:    
            cart = carts_models.Cart.objects.get(cart_id=__cart_id(request))
            cart_items = carts_models.CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            totalPay += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = 0.2 * totalPay
        grand_totalPay = totalPay + tax
    except ObjectDoesNotExist:
        pass

    context = {
        'totalPay': totalPay,
        'qunatity': quantity,
        'cart_items': cart_items,
        'grand_totalPay': round(grand_totalPay, 2),
        'taxPay': round(tax, 2)
    }

    return render(request, 'store/cart.html', context=context)


def add_cart(request, product_id):
    current_user = request.user
    if current_user.is_authenticated:
            product = store_models.Product.objects.get(id=product_id)
            product_variation = []
            if request.method == 'POST':
                for item in request.POST:
                    key = item
                    value = request.POST[key]

                    try:
                        variation = store_models.Variation.objects.get(product__id=product_id, variation_category__iexact=key, variation_value__iexact=value)
                        product_variation.append(variation)
                    except:
                        pass
            
            
            product_variation.sort(key=lambda x: x.variation_category)
                       
            is_cart_item_exist = carts_models.CartItem.objects.filter(product=product, user=current_user).exists()
            if is_cart_item_exist:
                cart_items = carts_models.CartItem.objects.all().filter(product=product, user=current_user)
                
                ex_var_list = []
                id_list = []
                for item in cart_items:
                    existing_variation = list(item.variation.all())
                    existing_variation.sort(key=lambda x : x.variation_category)
                    ex_var_list.append(existing_variation)
                    id_list.append(item.id)
                
                if product_variation in ex_var_list:
                    index = ex_var_list.index(product_variation)
                    item_id = id_list[index]
                    item = carts_models.CartItem.objects.get(
                        product=product, id=item_id)
                    item.quantity += 1
                    item.save()
                       
                else:
                    item = carts_models.CartItem.objects.create(
                        product=product, quantity=1, user=current_user)
                    if len(product_variation) > 0:
                        item.variation.clear()
                        item.variation.add(*product_variation)
                        item.quantity = 1
                    item.save()
            else:
                cart_item = carts_models.CartItem.objects.create(
                    product=product,
                    quantity=1,
                    user=current_user
                  
                )
                cart_item.save()
                if len(product_variation) > 0:
                    cart_item.variation.clear()
                    cart_item.variation.add(*product_variation)
 
            return redirect('cart-page')
    else:
        product = store_models.Product.objects.get(id=product_id)
        product_variation = []
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]

                try:
                    variation = store_models.Variation.objects.get(product__id=product_id,
                                                                variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass

        product = store_models.Product.objects.get(id=product_id)
        cart = None

        try:
            cart = carts_models.Cart.objects.get(cart_id=__cart_id(request))
        except carts_models.Cart.DoesNotExist as e:
            cart = carts_models.Cart.objects.create(cart_id=__cart_id(request))
        cart.save()

        is_cart_item_exist = carts_models.CartItem.objects.filter(
            product=product, cart=cart).exists()

        if is_cart_item_exist:
            cart_items = carts_models.CartItem.objects.filter(
                product=product, cart=cart)
            
            
            
            ex_var_list = []
            id_list = []
            for item in cart_items:
                existing_variation = item.variation.all()
                ex_var_list.append(list(existing_variation))
                id_list.append(item.id)





            if product_variation in ex_var_list:
                index = ex_var_list.index(product_variation)
                item_id = id_list[index]
                item = carts_models.CartItem.objects.get(
                    product=product, id=item_id)
                item.quantity += 1
                item.save()
                
                
            else:
                item = carts_models.CartItem.objects.create(
                    product=product, quantity=1, cart=cart)
                if len(product_variation) > 0:
                    item.variation.clear()
                    item.variation.add(*product_variation)
                    item.quantity = 1
                item.save()
        else:
            cart_item = carts_models.CartItem.objects.create(
                product=product,
                quantity=1,
                cart=cart
            )
            cart_item.save()
            if len(product_variation) > 0:
                cart_item.variation.clear()
                cart_item.variation.add(*product_variation)

        return redirect('cart-page')


def subtract_cart(request, product_id, cart_item_id):
    current_user = request.user
    if current_user.is_authenticated:
        product = get_object_or_404(store_models.Product, id=product_id)
        try:
            cart_item = carts_models.CartItem.objects.get(product=product, user=current_user, id=cart_item_id)

            if cart_item.quantity > 1:
                cart_item.quantity -= 1
                cart_item.save()
            else:
                cart_item.delete()

        except:
            pass
    else:    
        cart = carts_models.Cart.objects.get(cart_id=__cart_id(request))
        product = get_object_or_404(store_models.Product, id=product_id)
        try:
            cart_item = carts_models.CartItem.objects.get(
                product=product, cart=cart, id=cart_item_id)

            if cart_item.quantity > 1:
                cart_item.quantity -= 1
                cart_item.save()
            else:
                cart_item.delete()

        except:
            pass

    return redirect('cart-page')



def remove_item(request, product_id, cart_item_id):
    current_user = request.user
    if current_user.is_authenticated:
        try:

            product = get_object_or_404(store_models.Product, id=product_id)
            cart_item = carts_models.CartItem.objects.get(product=product, user=current_user, id = cart_item_id)
            cart_item.delete()
        except:
            print('Throw except in delete')
            pass
    else:
        try:
            cart = carts_models.Cart.objects.get(cart_id=__cart_id(request))
            product = get_object_or_404(store_models.Product, id=product_id)
            cart_item = carts_models.CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
            cart_item.delete()
        except:
            pass    
    return redirect('cart-page')




@login_required(login_url='login')
def check_out(request, total=0, quantity=0, cart_items=None):
    grand_totalPay = 0.0
    tax = 0.0
    try:
        if request.user.is_authenticated:
            cart_items = carts_models.CartItem.objects.filter(user = request.user, is_active = True)
            for cart_item in cart_items:
                total += (cart_item.product.price * cart_item.quantity)
                quantity += cart_item.quantity
            tax = 0.2 * total
            grand_totalPay = total + tax
        else:    
            cart = carts_models.Cart.objects.get(cart_id=__cart_id(request))
            cart_items = carts_models.CartItem.objects.filter(cart=cart, is_active=True)
            for cart_item in cart_items:
                total += (cart_item.product.price * cart_item.quantity)
                quantity += cart_item.quantity
            tax = 0.2 * total
            grand_totalPay = total + tax  
    except ObjectDoesNotExist:
        pass
   
    context = {
        'totalPay': total,
        'qunatity': quantity,
        'cart_items': cart_items,
        'grand_totalPay': round(grand_totalPay, 2),
        'taxPay': round(tax, 2)
    }
    
    return render(request, 'store/checkout.html', context)

store/templates/store/cart.html
{% extends 'greatKart/_base.html' %} {% load static %} {% block content %}

<section class="section-content padding-y bg">
  <div class="container">
    <!-- ============================ COMPONENT 1 ================================= -->
    {% if not cart_items %}
    <h2 class="text-center">Your Shopping Cart is Empty</h2>
    <br />
    <div class="text-center">
      <a href="{% url 'store-page' %}" class="btn btn-primary">
        Continue Shopping
      </a>
    </div>
    {% else %}
    <div class="row">
      <aside class="col-lg-9">
        <div class="card">
          <table class="table table-borderless table-shopping-cart">
            <thead class="text-muted">
              <tr class="small text-uppercase">
                <th scope="col">Product</th>
                <th scope="col" width="120">Quantity</th>
                <th scope="col" width="120">Price</th>
                <th scope="col" class="text-right" width="200"></th>
              </tr>
            </thead>
            <tbody>
              {% for item in cart_items %}
              <tr>
                <td>
                  <figure class="itemside align-items-center">
                    <a href="{{ item.product.get_url }}">
                      <div class="aside">
                        <img
                          src="{{ item.product.image.url }}"
                          class="img-sm"
                        />
                      </div>
                    </a>
                    <figcaption class="info">
                      <a
                        href="{{ item.product.get_url }}"
                        class="title text-dark"
                        >{{ item.product.product_name }}</a
                      >
                      <p class="text-muted small">
                        {% if item.variation.all %} 
						{% for i in item.variation.all %}
                        <span
                          >{{i.variation_category | capfirst }} : {{i.variation_value | capfirst }}
                        </span>
                        <br />
						{% endfor %}
						 {% endif %}
                      </p>
                    </figcaption>
                  </figure>
                </td>
                <td>
                  <!-- col.// -->
                  <div class="col">
                    <div class="input-group input-spinner">
                      <div class="input-group-prepend">
                        <form
                          action="{% url 'subtract-cart' item.product.id item.id %}"
                          method="post"
                        >
                          {% csrf_token %} {% for item in item.variation.all %}
                          <input
                            type="hidden"
                            name="{{ item.variation_category | lower }}"
                            value="{{ item.variation_value | capfirst}}"
                          />
                          {% endfor %}
                          <button
                            class="btn btn-light"
                            type="submit"
                            id="button-plus"
                          >
                            <i class="fa fa-minus"></i>
                          </button>
                        </form>
                      </div>
                      <input
                        type="text"
                        class="form-control"
                        value="{{ item.quantity }}"
                      />

                      <div class="input-group-append">
                        <form
                          action="{% url 'add-to-cart' item.product.id %}"
                          method="post"
                        >
                          {% csrf_token %}
						  {% for item in item.variation.all %}
                          <input
                            type="hidden"
                            name="{{ item.variation_category | lower }}"
                            value="{{ item.variation_value | capfirst}}"
                          />
                          {% endfor %}
                          <button
                            class="btn btn-light"
                            type="submit"
                            id="button-minus"
                          >
                            <i class="fa fa-plus"></i>
                          </button>
                        </form>
                      </div>
                    </div>
                    <!-- input-group.// -->
                  </div>
                  <!-- col.// -->
                </td>
                <td>
                  <div class="price-wrap">
                    <var class="price">${{ item.sub_total }}</var>
                    <small class="text-muted">
                      ${{ item.product.price }} each
                    </small>
                  </div>
                  <!-- price-wrap .// -->
                </td>
                <td class="text-right">
                  <a
                    href="{% url 'delete-cart-item' item.product.id item.id %}"
                    onclick="return confirm('Confirm if you want to delete {{item.product.product_name}}')"
                    class="btn btn-danger"
                  >
                    Remove
				</a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <!-- card.// -->
      </aside>
      <!-- col.// -->
      <aside class="col-lg-3">
        <div class="card">
          <div class="card-body">
            <dl class="dlist-align">
              <dt>Total price:</dt>
              <dd class="text-right">${{ totalPay }}</dd>
            </dl>
            <dl class="dlist-align">
              <dt>Tax:</dt>
              <dd class="text-right">${{taxPay}}</dd>
            </dl>
            <dl class="dlist-align">
              <dt>You will pay:</dt>
              <dd class="text-right text-dark b">
                <strong>${{ grand_totalPay }}</strong>
              </dd>
            </dl>
            <hr />
            <p class="text-center mb-3">
              <img src="{% static './images/misc/payments.png' %}" height="26" />
            </p>
            <a href="{% url 'checkout' %}" class="btn btn-primary btn-block">
              Checkout
            </a>
            <a href="{% url 'store-page' %}" class="btn btn-light btn-block"
              >Continue Shopping</a
            >
          </div>
          <!-- card-body.// -->
        </div>
        <!-- card.// -->
      </aside>
      <!-- col.// -->
    </div>
    <!-- row.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    {% endif %}
  </div>
  <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock content %}

store/templates/store/product_detail.html
{% extends 'greatKart/_base.html' %}
{% load static %}


{% block content %}

<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->
<div class="card">
	<div class="row no-gutters">
		<aside class="col-md-6">
					<article class="gallery-wrap"> 
						<div class="img-big-wrap mainImage">
						<center>
						<img src="{{ product.image.url }}">
						</center>
						</div> <!-- img-big-wrap.// -->
						
					</article> <!-- gallery-wrap .end// -->
					<ul class="thumb">
						<li>
							<a href="{{ product.image.url }}" target="mainImage">
								<img src="{{ product.image.url }}" alt="ProductImage">
							</a>
							{% for i in product_gallery %}
							<a href="{{ i.image.url }}" target="mainImage">
								<img src="{{ i.image.url }}" alt="ProductImage">
							</a>
							{% endfor %}
						</li>
					</ul>
		</aside>
<main class="col-md-6 border-left">

	<form action="{% url 'add-to-cart' product.id  %}" method="POST">
			{% csrf_token %}
			<article class="content-body">

			<h2 class="title">{{ product.product_name }}</h2>
			{% if reviewExist %}
				<span style='color: gold;'>
					{% with avg=product.averageReview %}
					<!-- Star 1 -->
					<i class="{% if avg >= 1 %}fas fa-star{% elif avg >= 0.5 %}fas fa-star-half-alt{% else %}far fa-star{% endif %}"></i>
					
					<!-- Star 2 -->
					<i class="{% if avg >= 2 %}fas fa-star{% elif avg >= 1.5 %}fas fa-star-half-alt{% else %}far fa-star{% endif %}"></i>
					
					<!-- Star 3 -->
					<i class="{% if avg >= 3 %}fas fa-star{% elif avg >= 2.5 %}fas fa-star-half-alt{% else %}far fa-star{% endif %}"></i>
					
					<!-- Star 4 -->
					<i class="{% if avg >= 4 %}fas fa-star{% elif avg >= 3.5 %}fas fa-star-half-alt{% else %}far fa-star{% endif %}"></i>
					
					<!-- Star 5 -->
					<i class="{% if avg >= 5 %}fas fa-star{% elif avg >= 4.5 %}fas fa-star-half-alt{% else %}far fa-star{% endif %}"></i>
					{% endwith %}
				</span>
				<span>{{ product.countReview }} review </span>
			{% endif %}				
			<div class="mb-3"> 
				<var class="price h4">${{ product.price }}</var> 
			</div> 

			<p>{{ product.description }}</p>

			<hr>

				<div class="row">
					<div class="item-option-select">
						<h6>Select color</h6>
						<select name="color" class="control-form"  required>
							<option value="" disabled selected>Choose Color</option>
							{% for var in product.variation_set.colors %}
							<option value="{{ var.variation_value  }}">{{ var.variation_value | capfirst }}</option>
							{% endfor %}
						</select>
					</div>
				</div> <!-- row.// -->
				<div class="row">
					<div class="item-option-select">
						<h6>Select Size</h6>
						<select name="size" class="control-form" required>
							<option value="" disabled selected>Choose Size</option>											
							{% for var in product.variation_set.sizes %}
								<option value="{{ var.variation_value }}">{{ var.variation_value | capfirst }}</option>
							{% endfor %}
						</select>								
					</div>
				</div>

			<!-- row.// -->
			<hr>
			{% if product.is_available %}
					<button type="submit"  class="btn  btn-primary"> <span class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i></button>
					<a  href="{% url 'cart-page' %}" class="btn btn-outline-primary">View Cart <i class="fas fa-eye"></i></a>
			{% else %}
				<span class="btn btn-secondary text">Out of Stock</span> <i class="fas fa-shopping-cart"></i> 
			{% endif %}
		</article> <!-- product-info-aside .// -->


	</form>

</main> <!-- col.// -->
</div> <!-- row.// -->
</div> <!-- card.// -->
<!-- ============================ COMPONENT 1 END .// ================================= -->

<br>

<div class="row">
	<div class="col-md-9">

	<header class="section-heading">
		<h3>Customer Reviews </h3>  
		
	</header>
	<h6>{{ product.countReview }} reviews </h6>
	{% if user.is_authenticated %}

	{% if is_product_ordered %}
	<form action="{% url 'submit-review' product.id %}" method="post">
		{% csrf_token %}
		<h5>Write Your Review about this </h5>
		<div class='container form-group'>
			<!--- Rating stars  -->
			<label for="">How do you rate this product?</label>
			<br>
			<div class="rate">
				<input type="radio" name="rating" id="rating10" value="5" required>  <label for="rating10" title="5"  class="" ></label>
				<input type="radio" name="rating" id="rating9" value="4.5" required> <label for="rating9" title="4.5" class="half" ></label>
				<input type="radio" name="rating" id="rating8" value="4" required>   <label for="rating8" title="4"   class="" ></label>
				<input type="radio" name="rating" id="rating7" value="3.5" required> <label for="rating7" title="3.5" class="half" ></label>
				<input type="radio" name="rating" id="rating6" value="3" required>   <label for="rating6" title="3"   class="" ></label>
				<input type="radio" name="rating" id="rating5" value="2.5" required> <label for="rating5" title="2.5" class="half" ></label>
				<input type="radio" name="rating" id="rating4" value="2" required>   <label for="rating4" title="2"   class="" ></label>
				<input type="radio" name="rating" id="rating3" value="1.5" required> <label for="rating3" title="1.5" class="half" ></label>
				<input type="radio" name="rating" id="rating2" value="1" required>   <label for="rating2" title="1"   class="" ></label>
				<input type="radio" name="rating" id="rating1" value="0.5" required> <label for="rating1" title="0.5" class="half" ></label>
			</div>
			<br>
			Review Title:
			<input type="text" class="form-control" name="subject">
			<br>
			Review:
			<textarea class="form-control" name="review" row="5"></textarea>
			<br>
			
			<button  type="submit" value="Submit Review" class="btn btn-primary" >Submit Review </button>
		</div>
		{% include 'greatKart/includes/alerts.html' %}
	</form>
	{% else %}
	<span>
	<h5>You need to buy this product in order to sumbit you review</h5>
	</span>
	<br>
	{% endif %}
	{% else %}
	<div class="container">
		<a class="btn btn-info" href="{% url 'login' %}">Login to post a review</a>
	</div>
		<br>
	{% endif %}
	
	{% if reviewExist %}

	{% for review in reviews %}
	<article class="box mb-3">
		<div class="icontext w-100">
			<div class="text">
				<span class="date text-muted float-md-right">{{ review.created_date }} </span>  
				<h6 class="mb-1"> {{ review.user.full_name }}</h6>
				<br>
					<span style='color: gold;'>
						<i class="{% if review.rating == 0.5 %}fas fa-star-half-alt{% elif review.rating >= 1 %}fas fa-star{% endif %}" aria-hidden='true'></i>
						<i class="{% if review.rating == 1.5 %}fas fa-star-half-alt{% elif review.rating >= 2 %}fas fa-star{% endif %}" aria-hidden='true'></i>
						<i class="{% if review.rating == 2.5 %}fas fa-star-half-alt{% elif review.rating >= 3 %}fas fa-star{% endif %}" aria-hidden='true'></i>
						<i class="{% if review.rating == 3.5 %}fas fa-star-half-alt{% elif review.rating >= 4 %}fas fa-star{% endif %}" aria-hidden='true'></i>
						<i class="{% if review.rating == 4.5 %}fas fa-star-half-alt{% elif review.rating >= 5 %}fas fa-star{% endif %}" aria-hidden='true'></i>
					</span>
			</div>
		</div> <!-- icontext.// -->
		<div class="mt-3">
				<p>
				Subject: 
					<span>
						{{ review.subject }}
					</span>
				</p>
	
			<hr>
			<p>
				{{ review.review }}
			</p>	
		</div>
	</article>
	{% endfor %}
	{% else %}
	<h4>There is no review found to be submmited for this product</h4>
	{% endif %}
	</div> <!-- col.// -->
</div> <!-- row.// -->


</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock content %}